# Config file
# Keep inventory true or false
KeepInventory: true

# Message types: chat, popup, tip, title

MessageType: chat

# Message after player's inventory has been kept
# You can use '&' to make colored text

MessageAfterDeath: "&aYour inventory has been kept"
